"""
Team-name normalization: map The Odds API team names onto the naming
convention used by the football-data.co.uk CSVs (which is what the ML
pipeline keys off).

Only teams that differ need an entry. Unmapped names fall through
unchanged — fail-loud is intentional: if a team's ratings can't be
found downstream, the mapping is the first place to check.
"""
from __future__ import annotations

# Keyed by league, then Odds-API name → CSV name.
_MAPPING: dict[str, dict[str, str]] = {
    "PL": {
        "Manchester United": "Man United",
        "Manchester City": "Man City",
        "Newcastle United": "Newcastle",
        "Tottenham Hotspur": "Tottenham",
        "Wolverhampton Wanderers": "Wolves",
        "Nottingham Forest": "Nott'm Forest",
        "Brighton and Hove Albion": "Brighton",
        "West Ham United": "West Ham",
        "Leicester City": "Leicester",
        "Leeds United": "Leeds",
        "Ipswich Town": "Ipswich",
        "Sheffield United": "Sheffield United",
        "Luton Town": "Luton",
    },
    "CH": {
        "Sheffield Wednesday": "Sheffield Weds",
        "Queens Park Rangers": "QPR",
        "West Bromwich Albion": "West Brom",
        "Preston North End": "Preston",
        "Blackburn Rovers": "Blackburn",
        "Bristol City": "Bristol City",
        "Cardiff City": "Cardiff",
        "Coventry City": "Coventry",
        "Derby County": "Derby",
        "Hull City": "Hull",
        "Leeds United": "Leeds",
        "Luton Town": "Luton",
        "Norwich City": "Norwich",
        "Plymouth Argyle": "Plymouth",
        "Stoke City": "Stoke",
        "Swansea City": "Swansea",
        "Birmingham City": "Birmingham",
        "Oxford United": "Oxford",
    },
    "BL": {
        "Bayern Munich": "Bayern Munich",
        "FC Bayern München": "Bayern Munich",
        "Borussia Dortmund": "Dortmund",
        "BVB Borussia Dortmund": "Dortmund",
        "Bayer Leverkusen": "Leverkusen",
        "Bayer 04 Leverkusen": "Leverkusen",
        "RB Leipzig": "RB Leipzig",
        "Eintracht Frankfurt": "Ein Frankfurt",
        "VfB Stuttgart": "Stuttgart",
        "SC Freiburg": "Freiburg",
        "1. FC Union Berlin": "Union Berlin",
        "Union Berlin": "Union Berlin",
        "Werder Bremen": "Werder Bremen",
        "SV Werder Bremen": "Werder Bremen",
        "1. FSV Mainz 05": "Mainz",
        "FSV Mainz 05": "Mainz",
        "Mainz 05": "Mainz",
        "TSG Hoffenheim": "Hoffenheim",
        "1899 Hoffenheim": "Hoffenheim",
        "Borussia Mönchengladbach": "M'gladbach",
        "Borussia M'gladbach": "M'gladbach",
        "VfL Wolfsburg": "Wolfsburg",
        "FC Augsburg": "Augsburg",
        "1. FC Heidenheim": "Heidenheim",
        "1. FC Köln": "FC Koln",
        "FC Köln": "FC Koln",
        "1. FC Koeln": "FC Koln",
        "FC St. Pauli": "St Pauli",
        "St. Pauli": "St Pauli",
        "Holstein Kiel": "Holstein Kiel",
        "VfL Bochum": "Bochum",
        "FC Schalke 04": "Schalke 04",
        "Hamburger SV": "Hamburg",
        "Hertha BSC": "Hertha",
    },
    "SA": {
        "Internazionale": "Inter",
        "Inter Milan": "Inter",
        "AC Milan": "Milan",
        "AS Roma": "Roma",
        "SS Lazio": "Lazio",
        "SSC Napoli": "Napoli",
        "Juventus Turin": "Juventus",
        "ACF Fiorentina": "Fiorentina",
        "Atalanta BC": "Atalanta",
        "Bologna FC": "Bologna",
        "Torino FC": "Torino",
        "Hellas Verona": "Verona",
        "Udinese Calcio": "Udinese",
        "Empoli FC": "Empoli",
        "US Lecce": "Lecce",
        "Parma Calcio 1913": "Parma",
        "Venezia FC": "Venezia",
        "Cagliari Calcio": "Cagliari",
        "Monza": "Monza",
        "Genoa CFC": "Genoa",
        "Como 1907": "Como",
        "US Sassuolo": "Sassuolo",
        "US Cremonese": "Cremonese",
        "US Salernitana 1919": "Salernitana",
        "Pisa SC": "Pisa",
    },
    "LL": {
        "Atletico Madrid": "Ath Madrid",
        "Atlético Madrid": "Ath Madrid",
        "Athletic Bilbao": "Ath Bilbao",
        "Athletic Club": "Ath Bilbao",
        "Real Betis": "Betis",
        "Real Sociedad": "Sociedad",
        "Celta Vigo": "Celta",
        "RC Celta": "Celta",
        "Deportivo Alaves": "Alaves",
        "Deportivo Alavés": "Alaves",
        "Rayo Vallecano": "Vallecano",
        "UD Las Palmas": "Las Palmas",
        "CA Osasuna": "Osasuna",
        "RCD Mallorca": "Mallorca",
        "Real Valladolid": "Valladolid",
        "RCD Espanyol": "Espanol",
        "Espanyol": "Espanol",
        "Girona FC": "Girona",
        "Getafe CF": "Getafe",
        "Villarreal CF": "Villarreal",
        "Sevilla FC": "Sevilla",
        "Valencia CF": "Valencia",
        "Real Oviedo": "Oviedo",
        "Levante UD": "Levante",
        "Elche CF": "Elche",
    },
}


def normalize(league_key: str, team: str) -> str:
    """Return the CSV-canonical team name, or the input unchanged."""
    return _MAPPING.get(league_key, {}).get(team, team)
